language: python
python:
  - "2.7"
addons:
  apt:
    packages:
    - python-mysqldb

# command to install dependencies
before_install:
  - mkdir output
  - mysql -e 'create database database_name;'
  - pip install -q flake8
  - pip install PyMySQL
  - pip install mysql-python

install:
  - pip install -q mysql-python
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - nosetests

after_success:
  - coverage run --include=test_models.py  test_models.py
  - coverage combine
  - coveralls

services:
  - mysql

env:
  MUCKAMUCK_OUTPUT_DIRECTORY="output"
  MUCKAMUCK_DB_HOST="127.0.0.1"
  MUCKAMUCK_DB_NAME="database_name"
  MUCKAMUCK_DB_USER_NAME="travis"
  MUCKAMUCK_DB_USER_PASSWORD=""
